apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  selector:
    app: flask
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  # number of pods that kubernetes will create of this deployment 
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      # TODO: edit it to be the docker hub or other registry image name
      - name: flask
        image: flask:latest 