services:
  # edit this to be what you want

  # nextjs frontend
  nextjs-frontend:
    build:
      context: ./nextjs-frontend-example
      dockerfile: ../dockerfiles/frontend.dev.dockerfile

    # Set environment variables directly in the compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    volumes:
      - ./nextjs-frontend-example/src:/app/src
      - ./nextjs-frontend-example/public:/app/public
    ports:
      - 3000:3000

  # fastapi backend
  fastapi-backend:
    build:
      context: ./fastapi-backend-example
      dockerfile: ../dockerfiles/fastapi.dev.dockerfile
    volumes:
      - ./fastapi-backend-example:/app
    ports:
      - 8000:8000

  # flask backend
  flask-backend:
    build:
      context: ./flask-backend-example
      dockerfile: ../dockerfiles/flask.dev.dockerfile
    volumes:
      - ./flask-backend-example:/app
    ports:
      - 5000:5000

  # nodejs backend
  nodejs-backend:
    build:
      context: ./nodejs-backend-example
      dockerfile: ../dockerfiles/node.dev.dockerfile
    volumes:
      - ./nodejs-backend-example:/app
    ports:
      - 4000:4000